# Generated by Django 6.1 on 2026-08-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'Новое'), ('used', 'Б/у')], default='new', max_length=10),
        ),
    ]
