# Generated by Django 6.1 on 2026-08-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='article',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
